# action.yaml
name: 'pre-commit-dbt'
description: 'List of pre-commit hooks to ensure the quality of your dbt projects.'
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  flag:
    description: 'flag for pre-commit'
    required: false
    default: '--all-files'
  files:
    description: 'files to evaluate'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - run
    - -c
    - .pre-commit-config-ci.yaml
    - ${{ inputs.flag}}
    - ${{ inputs.files}}
